kind: Service
apiVersion: v1
metadata:
  name: prometheus
  namespace: kube-system
  labels:
    app: prometheus
spec:
  type: NodePort
  ports:
  - port: 9090
    targetPort: 9090
    nodePort: 30003
  selector:
    app: prometheus
